# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Maven Build"

on:
  pull_request:
    branches: [master, release-*]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Maven Java 16"
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-java16-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-java16
      - name: Set Maven Options 
        env:
          MAVEN_OPTS: --add-opens=java.base/sun.security.x509=ALL-UNNAMED
      - name: Build with Maven
        run: mvn -DargLine="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:GCTimeRatio=99" -B clean verify --file pom.xml
      - name: Upload assemblies
        uses: actions/upload-artifact@v2
        with:
          name: Assemblies
          path: |
            distribution/target/*.jar
            ia-clientlibrary/target/*.jar
            igc-clientlibrary/target/*.jar
